/**
 * Finance Report Generator - Template Definitions
 * Module 2: 40 Finance Report Templates across 4 categories
 * 
 * Categories:
 * 1. Collection Reports (15)
 * 2. Outstanding Reports (10)
 * 3. Concession & Scholarship (8)
 * 4. Financial Analysis (7)
 */

import { getColumnsForSet } from './columns';

// ═══════════════════════════════════════════════════════════════════════════════
// TEMPLATE DEFINITIONS
// ═══════════════════════════════════════════════════════════════════════════════

export const FINANCE_TEMPLATES = [
  // ─────────────────────────────────────────────────────────────────────────────
  // CATEGORY 1: COLLECTION REPORTS (15)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'daily_collection_summary',
    name: 'Daily Collection Summary',
    description: 'Day-wise breakdown of fee collection by payment mode',
    category: 'collection',
    icon: '📅',
    columns: getColumnsForSet('daily_collection'),
    defaultFilters: { date_range: 'today' },
    defaultGroupBy: ['date'],
    defaultSortBy: [{ field: 'date', direction: 'desc' }],
    aggregations: ['total_collection', 'payment_count'],
    popular: true,
  },
  {
    id: 'monthly_collection',
    name: 'Monthly Collection Report',
    description: 'Month-wise collection with fee head breakdown',
    category: 'collection',
    icon: '📊',
    columns: getColumnsForSet('monthly_collection'),
    defaultFilters: { month: 'current' },
    defaultGroupBy: ['month'],
    defaultSortBy: [{ field: 'month', direction: 'asc' }],
    aggregations: ['total_collection'],
    popular: true,
  },
  {
    id: 'class_wise_collection',
    name: 'Class-wise Collection',
    description: 'Fee collection summary grouped by class',
    category: 'collection',
    icon: '🏫',
    columns: getColumnsForSet('class_wise_collection'),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'class_name', direction: 'asc' }],
    aggregations: ['total_fee', 'paid_amount', 'balance'],
    popular: true,
  },
  {
    id: 'section_wise_collection',
    name: 'Section-wise Collection',
    description: 'Detailed collection by class and section',
    category: 'collection',
    icon: '📚',
    columns: getColumnsForSet('section_wise_collection'),
    defaultFilters: {},
    defaultGroupBy: ['class_name', 'section_name'],
    defaultSortBy: [{ field: 'class_name', direction: 'asc' }],
    aggregations: ['total_fee', 'paid_amount'],
  },
  {
    id: 'fee_head_collection',
    name: 'Fee Head-wise Collection',
    description: 'Collection analysis by fee type/head',
    category: 'collection',
    icon: '💳',
    columns: getColumnsForSet('fee_head_collection'),
    defaultFilters: {},
    defaultGroupBy: ['fee_head'],
    defaultSortBy: [{ field: 'total_fee', direction: 'desc' }],
    aggregations: ['total_fee', 'paid_amount'],
  },
  {
    id: 'payment_mode_analysis',
    name: 'Payment Mode Analysis',
    description: 'Collection breakdown by payment mode (Cash, Online, etc.)',
    category: 'collection',
    icon: '💰',
    columns: getColumnsForSet('payment_mode'),
    defaultFilters: {},
    defaultGroupBy: ['payment_mode'],
    defaultSortBy: [{ field: 'amount', direction: 'desc' }],
    aggregations: ['amount', 'payment_count'],
    popular: true,
  },
  {
    id: 'cashier_wise_collection',
    name: 'Cashier-wise Collection',
    description: 'Collection summary by fee collector/cashier',
    category: 'collection',
    icon: '👤',
    columns: getColumnsForSet('cashier_wise'),
    defaultFilters: { date_range: 'today' },
    defaultGroupBy: ['cashier_name'],
    defaultSortBy: [{ field: 'total_collection', direction: 'desc' }],
    aggregations: ['receipt_count', 'total_collection'],
  },
  {
    id: 'hour_wise_collection',
    name: 'Hour-wise Collection',
    description: 'Hourly distribution of fee collection',
    category: 'collection',
    icon: '⏰',
    columns: getColumnsForSet('hour_wise_collection'),
    defaultFilters: { date_range: 'today' },
    defaultGroupBy: ['collection_hour'],
    defaultSortBy: [{ field: 'collection_hour', direction: 'asc' }],
    aggregations: ['payment_count', 'total_collection'],
  },
  {
    id: 'receipt_register',
    name: 'Receipt Register',
    description: 'Complete receipt log with all payment details',
    category: 'collection',
    icon: '📝',
    columns: getColumnsForSet('receipt_register'),
    defaultFilters: {},
    defaultGroupBy: [],
    defaultSortBy: [{ field: 'receipt_no', direction: 'desc' }],
    aggregations: ['amount'],
    popular: true,
  },
  {
    id: 'cancelled_receipts',
    name: 'Cancelled Receipts',
    description: 'List of cancelled receipts with reasons',
    category: 'collection',
    icon: '❌',
    columns: getColumnsForSet('cancelled_receipts'),
    defaultFilters: {},
    defaultGroupBy: ['cancel_reason'],
    defaultSortBy: [{ field: 'cancelled_date', direction: 'desc' }],
    aggregations: ['amount'],
  },
  {
    id: 'cheque_collection',
    name: 'Cheque Collection Report',
    description: 'All cheque payments with bank and clearance status',
    category: 'collection',
    icon: '🏦',
    columns: getColumnsForSet('cheque_collection'),
    defaultFilters: {},
    defaultGroupBy: ['cheque_status'],
    defaultSortBy: [{ field: 'cheque_date', direction: 'desc' }],
    aggregations: ['amount'],
  },
  {
    id: 'online_payments',
    name: 'Online Payment Report',
    description: 'Digital payments via payment gateways',
    category: 'collection',
    icon: '🌐',
    columns: getColumnsForSet('online_payments'),
    defaultFilters: {},
    defaultGroupBy: ['payment_gateway'],
    defaultSortBy: [{ field: 'date', direction: 'desc' }],
    aggregations: ['amount'],
    popular: true,
  },
  {
    id: 'partial_payments',
    name: 'Partial Payment Report',
    description: 'Students with incomplete fee payments',
    category: 'collection',
    icon: '📉',
    columns: getColumnsForSet('partial_payments'),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'balance', direction: 'desc' }],
    aggregations: ['total_fee', 'paid_amount', 'balance'],
  },
  {
    id: 'advance_fee_collection',
    name: 'Advance Fee Collection',
    description: 'Students who paid fees in advance',
    category: 'collection',
    icon: '⏩',
    columns: getColumnsForSet('advance_fee'),
    defaultFilters: {},
    defaultGroupBy: ['advance_for_month'],
    defaultSortBy: [{ field: 'advance_amount', direction: 'desc' }],
    aggregations: ['advance_amount'],
  },
  {
    id: 'late_fee_collection',
    name: 'Late Fee Collection',
    description: 'Late fee charges and collection',
    category: 'collection',
    icon: '⏱️',
    columns: getColumnsForSet('late_fee'),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'late_days', direction: 'desc' }],
    aggregations: ['late_fee', 'paid_amount'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // CATEGORY 2: OUTSTANDING REPORTS (10)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'fee_defaulters',
    name: 'Fee Defaulters List',
    description: 'Students with outstanding fee dues',
    category: 'outstanding',
    icon: '⚠️',
    columns: getColumnsForSet('fee_defaulters'),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'due_amount', direction: 'desc' }],
    aggregations: ['due_amount'],
    popular: true,
  },
  {
    id: 'balance_fee_statement',
    name: 'Balance Fee Statement',
    description: 'Complete fee status showing total, paid, and balance',
    category: 'outstanding',
    icon: '📋',
    columns: getColumnsForSet('balance_statement'),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'due_amount', direction: 'desc' }],
    aggregations: ['total_fee', 'paid_amount', 'due_amount'],
    popular: true,
  },
  {
    id: 'overdue_fee',
    name: 'Overdue Fee Report',
    description: 'Fees overdue with days classification',
    category: 'outstanding',
    icon: '🔴',
    columns: getColumnsForSet('overdue_fee'),
    defaultFilters: {},
    defaultGroupBy: ['overdue_category'],
    defaultSortBy: [{ field: 'overdue_days', direction: 'desc' }],
    aggregations: ['due_amount'],
    popular: true,
  },
  {
    id: 'month_outstanding',
    name: 'Month-wise Outstanding',
    description: 'Outstanding fee movement month by month',
    category: 'outstanding',
    icon: '📆',
    columns: getColumnsForSet('month_outstanding'),
    defaultFilters: {},
    defaultGroupBy: ['month'],
    defaultSortBy: [{ field: 'month', direction: 'asc' }],
    aggregations: ['opening_balance', 'collected', 'closing_balance'],
  },
  {
    id: 'class_outstanding',
    name: 'Class-wise Outstanding',
    description: 'Outstanding dues summarized by class',
    category: 'outstanding',
    icon: '🏫',
    columns: getColumnsForSet('class_outstanding'),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'due_amount', direction: 'desc' }],
    aggregations: ['total_fee', 'due_amount'],
  },
  {
    id: 'follow_up_report',
    name: 'Fee Follow-up Report',
    description: 'Contact history and follow-up status for defaulters',
    category: 'outstanding',
    icon: '📞',
    columns: getColumnsForSet('follow_up'),
    defaultFilters: {},
    defaultGroupBy: ['follow_up_status'],
    defaultSortBy: [{ field: 'promise_date', direction: 'asc' }],
    aggregations: ['due_amount'],
  },
  {
    id: 'high_defaulters',
    name: 'High Defaulters Alert',
    description: 'Students with dues above threshold (₹10,000+)',
    category: 'outstanding',
    icon: '🚨',
    columns: getColumnsForSet('high_defaulters'),
    defaultFilters: { min_due: 10000 },
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'due_amount', direction: 'desc' }],
    aggregations: ['due_amount'],
    popular: true,
  },
  {
    id: 'category_defaulters',
    name: 'Category-wise Defaulters',
    description: 'Defaulters grouped by student category',
    category: 'outstanding',
    icon: '📊',
    columns: getColumnsForSet('category_defaulters'),
    defaultFilters: {},
    defaultGroupBy: ['student_category'],
    defaultSortBy: [{ field: 'due_amount', direction: 'desc' }],
    aggregations: ['defaulter_count', 'due_amount'],
  },
  {
    id: 'rte_fee_pending',
    name: 'RTE Fee Pending',
    description: 'Government fee pending for RTE students',
    category: 'outstanding',
    icon: '🎓',
    columns: getColumnsForSet('rte_pending'),
    defaultFilters: { rte_status: 'yes' },
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'govt_pending', direction: 'desc' }],
    aggregations: ['rte_amount', 'govt_pending'],
  },
  {
    id: 'new_student_pending',
    name: 'New Student Fee Pending',
    description: 'Fee dues for newly admitted students',
    category: 'outstanding',
    icon: '🆕',
    columns: getColumnsForSet('new_student_pending'),
    defaultFilters: { is_new_student: true },
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'due_amount', direction: 'desc' }],
    aggregations: ['total_fee', 'due_amount'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // CATEGORY 3: CONCESSION & SCHOLARSHIP (8)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'concession_report',
    name: 'Concession Report',
    description: 'All fee concessions given to students',
    category: 'concession',
    icon: '🎁',
    columns: getColumnsForSet('concession_report'),
    defaultFilters: {},
    defaultGroupBy: ['concession_type'],
    defaultSortBy: [{ field: 'concession_amount', direction: 'desc' }],
    aggregations: ['concession_amount'],
    popular: true,
  },
  {
    id: 'scholarship_disbursement',
    name: 'Scholarship Disbursement',
    description: 'Scholarship allocation and disbursement status',
    category: 'concession',
    icon: '🏆',
    columns: getColumnsForSet('scholarship'),
    defaultFilters: {},
    defaultGroupBy: ['scholarship_name'],
    defaultSortBy: [{ field: 'scholarship_amount', direction: 'desc' }],
    aggregations: ['scholarship_amount'],
    popular: true,
  },
  {
    id: 'fee_waiver',
    name: 'Fee Waiver Report',
    description: 'Fee waivers with approval details',
    category: 'concession',
    icon: '✅',
    columns: getColumnsForSet('fee_waiver'),
    defaultFilters: {},
    defaultGroupBy: ['waiver_reason'],
    defaultSortBy: [{ field: 'waiver_amount', direction: 'desc' }],
    aggregations: ['waiver_amount'],
  },
  {
    id: 'staff_ward_concession',
    name: 'Staff Ward Concession',
    description: 'Fee concession for staff children',
    category: 'concession',
    icon: '👨‍👩‍👧',
    columns: getColumnsForSet('staff_ward'),
    defaultFilters: {},
    defaultGroupBy: ['staff_name'],
    defaultSortBy: [{ field: 'concession_amount', direction: 'desc' }],
    aggregations: ['concession_amount'],
  },
  {
    id: 'sibling_discount',
    name: 'Sibling Discount Report',
    description: 'Discounts for families with multiple siblings',
    category: 'concession',
    icon: '👫',
    columns: getColumnsForSet('sibling_discount'),
    defaultFilters: {},
    defaultGroupBy: [],
    defaultSortBy: [{ field: 'sibling_discount', direction: 'desc' }],
    aggregations: ['sibling_discount'],
  },
  {
    id: 'merit_scholarship',
    name: 'Merit Scholarship',
    description: 'Scholarships based on academic performance',
    category: 'concession',
    icon: '⭐',
    columns: getColumnsForSet('merit_scholarship'),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'marks_percentage', direction: 'desc' }],
    aggregations: ['scholarship_amount'],
  },
  {
    id: 'sports_quota',
    name: 'Sports Quota Concession',
    description: 'Concessions for sports achievers',
    category: 'concession',
    icon: '🏅',
    columns: getColumnsForSet('sports_quota'),
    defaultFilters: {},
    defaultGroupBy: ['sport_name'],
    defaultSortBy: [{ field: 'concession_amount', direction: 'desc' }],
    aggregations: ['concession_amount'],
  },
  {
    id: 'ews_bpl_concession',
    name: 'EWS/BPL Concession',
    description: 'Concessions for economically weaker sections',
    category: 'concession',
    icon: '🤝',
    columns: getColumnsForSet('ews_bpl'),
    defaultFilters: {},
    defaultGroupBy: ['economic_category'],
    defaultSortBy: [{ field: 'concession_amount', direction: 'desc' }],
    aggregations: ['concession_amount'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // CATEGORY 4: FINANCIAL ANALYSIS (7)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'revenue_projection',
    name: 'Revenue Projection',
    description: 'Expected vs actual collection with variance',
    category: 'analysis',
    icon: '📈',
    columns: getColumnsForSet('revenue_projection'),
    defaultFilters: {},
    defaultGroupBy: ['month'],
    defaultSortBy: [{ field: 'month', direction: 'asc' }],
    aggregations: ['expected_amount', 'collected_amount'],
    popular: true,
  },
  {
    id: 'year_comparison',
    name: 'Year-on-Year Comparison',
    description: 'Compare fee collection across years',
    category: 'analysis',
    icon: '📊',
    columns: getColumnsForSet('year_comparison'),
    defaultFilters: {},
    defaultGroupBy: ['fee_head'],
    defaultSortBy: [{ field: 'growth_percentage', direction: 'desc' }],
    aggregations: ['last_year_amount', 'this_year_amount'],
    popular: true,
  },
  {
    id: 'fee_structure_analysis',
    name: 'Fee Structure Analysis',
    description: 'Class and fee head-wise structure overview',
    category: 'analysis',
    icon: '🏗️',
    columns: getColumnsForSet('fee_structure'),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'class_name', direction: 'asc' }],
    aggregations: ['fee_amount', 'total_expected'],
  },
  {
    id: 'refund_report',
    name: 'Refund Report',
    description: 'Fee refunds processed with reasons',
    category: 'analysis',
    icon: '↩️',
    columns: getColumnsForSet('refund_report'),
    defaultFilters: {},
    defaultGroupBy: ['refund_reason'],
    defaultSortBy: [{ field: 'refund_date', direction: 'desc' }],
    aggregations: ['refund_amount'],
  },
  {
    id: 'journal_entries',
    name: 'Journal Entries',
    description: 'Accounting journal with debit/credit entries',
    category: 'analysis',
    icon: '📒',
    columns: getColumnsForSet('journal_entries'),
    defaultFilters: {},
    defaultGroupBy: ['entry_type'],
    defaultSortBy: [{ field: 'date', direction: 'desc' }],
    aggregations: ['debit', 'credit'],
  },
  {
    id: 'bank_reconciliation',
    name: 'Bank Reconciliation',
    description: 'Book vs bank balance reconciliation',
    category: 'analysis',
    icon: '🏦',
    columns: getColumnsForSet('bank_reconciliation'),
    defaultFilters: {},
    defaultGroupBy: [],
    defaultSortBy: [{ field: 'date', direction: 'desc' }],
    aggregations: ['book_balance', 'bank_balance'],
  },
  {
    id: 'gst_report',
    name: 'GST Report',
    description: 'GST breakdown (CGST, SGST, IGST)',
    category: 'analysis',
    icon: '📑',
    columns: getColumnsForSet('gst_report'),
    defaultFilters: {},
    defaultGroupBy: ['month'],
    defaultSortBy: [{ field: 'date', direction: 'desc' }],
    aggregations: ['taxable_amount', 'cgst', 'sgst', 'total_gst'],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY DEFINITIONS
// ═══════════════════════════════════════════════════════════════════════════════

export const FINANCE_CATEGORIES = [
  {
    id: 'collection',
    name: 'Collection Reports',
    icon: '💰',
    description: 'Fee collection and receipt reports',
    color: 'green',
    count: 15,
  },
  {
    id: 'outstanding',
    name: 'Outstanding Reports',
    icon: '⚠️',
    description: 'Defaulters and pending fee reports',
    color: 'red',
    count: 10,
  },
  {
    id: 'concession',
    name: 'Concession & Scholarship',
    icon: '🎁',
    description: 'Discounts, waivers, and scholarships',
    color: 'purple',
    count: 8,
  },
  {
    id: 'analysis',
    name: 'Financial Analysis',
    icon: '📈',
    description: 'Revenue projections and comparisons',
    color: 'blue',
    count: 7,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════════

// Get templates by category
export const getTemplatesByCategory = (categoryId) => {
  return FINANCE_TEMPLATES.filter(t => t.category === categoryId);
};

// Get popular templates
export const getPopularTemplates = () => {
  return FINANCE_TEMPLATES.filter(t => t.popular);
};

// Get template by ID
export const getTemplateById = (templateId) => {
  return FINANCE_TEMPLATES.find(t => t.id === templateId);
};

// Search templates
export const searchTemplates = (query) => {
  const lowerQuery = query.toLowerCase();
  return FINANCE_TEMPLATES.filter(t => 
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery)
  );
};

export default {
  FINANCE_TEMPLATES,
  FINANCE_CATEGORIES,
  getTemplatesByCategory,
  getPopularTemplates,
  getTemplateById,
  searchTemplates,
};

