export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    SCHOOL_LOGIN: '/school-login',
    SCHOOL_HOMEPAGE: '/school-homepage',
    DYNAMIC_SCHOOL_HOME: '/:schoolAlias',
    DYNAMIC_LOGIN: '/:schoolAlias/login',
    DYNAMIC_FORGOT_PASSWORD: '/:schoolAlias/forgot-password',
    DYNAMIC_SIGNUP: '/:schoolAlias/signup',
    DYNAMIC_EXAM_RESULT: '/:schoolAlias/exam-result',
    DYNAMIC_PAGE: '/:schoolAlias/pages/:pageSlug',
    DYNAMIC_EVENTS: '/:schoolAlias/events',
    DYNAMIC_NEWS: '/:schoolAlias/news',
    DYNAMIC_NEWS_DETAIL: '/:schoolAlias/news/:newsSlug',
    DYNAMIC_GALLERY: '/:schoolAlias/gallery',
    DYNAMIC_ONLINE_COURSE: '/:schoolAlias/online-course',
    DYNAMIC_ADMISSION: '/:schoolAlias/admission',
    DYNAMIC_ONLINE_ADMISSION: '/:schoolAlias/online-admission',
    DYNAMIC_CBSE_EXAM_RESULT: '/:schoolAlias/cbse-exam-result',
    DYNAMIC_SERVICES_HUB: '/:schoolAlias/services',
  },
  MASTER_ADMIN: {
    DASHBOARD: '/master-admin/dashboard',
    SCHOOLS: '/master-admin/schools',
    ORGANIZATION_REQUESTS: '/master-admin/organization-requests',
    SCHOOL_REQUESTS: '/master-admin/organization-requests', // Alias for backward compatibility
    CREATE_ORGANIZATION: '/master-admin/create-organization',
    ADD_SCHOOL: '/master-admin/add-school',
    EDIT_SCHOOL: '/master-admin/edit-school/:id',
    SCHOOL_DETAILS: '/master-admin/school-details/:id',
    SCHOOL_DETAILS_TAB: '/master-admin/school-details/:id/:tab',
    PROFILE: '/master-admin/profile',
    RESET_PASSWORD: '/master-admin/reset-password',
    SUBSCRIPTION_PLANS: '/master-admin/subscription-plans',
    ADD_SUBSCRIPTION_PLAN: '/master-admin/add-subscription-plan',
    EDIT_SUBSCRIPTION_PLAN: '/master-admin/edit-subscription-plan/:id',
    SUBSCRIPTIONS: '/master-admin/subscriptions',
    SUBSCRIPTION_INVOICES: '/master-admin/subscription-invoices',
    SUBSCRIPTION_TRANSACTIONS: '/master-admin/subscription-transactions',
    BILLING_AUDIT: '/master-admin/billing-audit',
    GENERATE_BILL: '/master-admin/subscriptions/bill/:branchId',
    BULK_INVOICE: '/master-admin/subscriptions/bulk-invoice', // New Bulk Invoice
    ROLE_PERMISSION: '/master-admin/role-permission',
    QUERIES_FINDER: '/master-admin/queries-finder', // New Module
    ASSIGN_PERMISSION: '/master-admin/assign-permission',
    ASSIGN_PERMISSION_ID: '/master-admin/assign-permission/:roleId',
    ASSIGN_PERMISSION_FULL: '/master-admin/assign-permission/:branchId/:roleId',
    COMMUNICATION_SETTINGS: '/master-admin/communication-settings',
    WHATSAPP_MANAGER: '/master-admin/whatsapp-manager',
    EMAIL_SETTINGS: '/master-admin/email-settings',
    PAYMENT_SETTINGS: '/master-admin/payment-settings',
    LOGIN_PAGE_SETTINGS: '/master-admin/login-page-settings',
    MASTER_SCHOOL_LOGIN_SETTINGS: '/master-admin/front-cms/school-login-settings',
    SESSION_SETTING: '/master-admin/session-setting',
    EXPORT_IMPORT: '/master-admin/export-import',
    MASTER_DATA_SETTINGS: '/master-admin/master-data-settings',
    SAAS_WEBSITE_SETTINGS: '/master-admin/saas-website-settings',
    FILE_MANAGER: '/master-admin/file-manager',

    FRONT_CMS: '/master-admin/front-cms/:tab?', // Dynamic Routing for Master Admin
    ARTICLES: '/master-admin/articles',
    CREATE_ARTICLE: '/master-admin/articles/new',
    EDIT_ARTICLE: '/master-admin/articles/edit/:id',
    VIEW_ARTICLE: '/master-admin/articles/:slug',
    ARTICLES_DOCS: '/master-admin/articles/documentation',
    MODULE_HEALTH: '/master-admin/module-health', 
    ENTERPRISE_HEALTH: '/master-admin/enterprise-health-monitor',
    DEMO_AUTOMATION: '/master-admin/demo-automation',
    DEMO_AUTOMATION_V2: '/master-admin/demo-automation-v2',
    SCHOOL_OWNER_DIAGNOSTICS: '/master-admin/school-owner-diagnostics',
    SYSTEM_SETTINGS: '/master-admin/settings'
  },
  SUPER_ADMIN: {
    DASHBOARD: '/super-admin/dashboard',
    PROFILE: '/super-admin/profile',
    RESET_PASSWORD: '/super-admin/reset-password',
    UPGRADE_TO_ORGANIZATION: '/super-admin/upgrade-to-organization',
    MY_SUBSCRIPTION: '/super-admin/my-subscription',
    // Front Office
    SETUP_FRONT_OFFICE: '/super-admin/front-office/setup',
    ADMISSION_ENQUIRY: '/super-admin/front-office/admission-enquiry',
    VISITOR_BOOK: '/super-admin/front-office/visitor-book',
    PHONE_CALL_LOG: '/super-admin/front-office/phone-call-log',
    POSTAL_DISPATCH: '/super-admin/front-office/postal-dispatch',
    POSTAL_RECEIVE: '/super-admin/front-office/postal-receive',
    COMPLAIN: '/super-admin/front-office/complain',
    // Gmeet
    GMEET_SETTING: '/super-admin/gmeet-live-classes/setting',
    LIVE_CLASSES: '/super-admin/gmeet-live-classes/live-classes',
    LIVE_MEETING: '/super-admin/gmeet-live-classes/live-meeting',
    LIVE_CLASSES_REPORT: '/super-admin/gmeet-live-classes/live-classes-report',
    LIVE_MEETING_REPORT: '/super-admin/gmeet-live-classes/live-meeting-report',
    // Online Course
    ONLINE_COURSE: '/super-admin/online-course',
    OFFLINE_PAYMENT: '/super-admin/online-course/offline-payment',
    ONLINE_COURSE_REPORT: '/super-admin/online-course/online-course-report',
    ONLINE_COURSE_SETTING: '/super-admin/online-course/setting',
    
    // --- FRONT CMS (Unified Editor Routing) ---
    FRONT_CMS_EDITOR: '/super-admin/front-cms', 
    CMS_SETTING: '/super-admin/front-cms/website-settings',
    MENUS: '/super-admin/front-cms/menus',
    MENU_ITEMS: '/super-admin/front-cms/menus/:menuId/items',
    PAGES: '/super-admin/front-cms/pages',
    EVENTS: '/super-admin/front-cms/events',
    GALLERY: '/super-admin/front-cms/gallery',
    NEWS: '/super-admin/front-cms/news',
    MEDIA_MANAGER: '/super-admin/front-cms/media-manager',
    BANNER_IMAGES: '/super-admin/front-cms/banners',
    BANNER: '/super-admin/front-cms/banner',
    CMS_SETTINGS: '/super-admin/front-cms/cms-settings',
    
    // Deprecated specific routes that are now handled by the dynamic editor
    // Retained as strings for compatibility if referenced elsewhere, but routing will handle them
    MENU_ITEMS: '/super-admin/front-cms/menus/items/:menuId', 
    ADD_PAGE: '/super-admin/front-cms/pages/add',
    EDIT_PAGE: '/super-admin/front-cms/pages/edit/:pageId',
    ADD_EVENT: '/super-admin/front-cms/events/add',
    EDIT_EVENT: '/super-admin/front-cms/events/edit/:eventId',
    ADD_GALLERY: '/super-admin/front-cms/gallery/add',
    EDIT_GALLERY: '/super-admin/front-cms/gallery/edit/:galleryId',
    ADD_NEWS: '/super-admin/front-cms/news/add',
    EDIT_NEWS: '/super-admin/front-cms/news/edit/:newsId',

    // Academics
    CLASSES: '/super-admin/academics/classes',
    SECTIONS: '/super-admin/academics/sections',
    SUBJECTS: '/super-admin/academics/subjects',
    SUBJECT_GROUP: '/super-admin/academics/subject-group',
    CLASS_TIMETABLE: '/super-admin/academics/class-timetable',
    TEACHER_TIMETABLE: '/super-admin/academics/teacher-timetable',
    TIMETABLE: '/super-admin/academics/timetable',
    CLASS_TEACHER: '/super-admin/academics/class-teacher',
    ASSIGN_CLASS_TEACHER: '/super-admin/academics/assign-class-teacher',
    PROMOTE_STUDENT: '/super-admin/academics/promote-student',
    SUBJECT_TEACHER: '/super-admin/academics/subject-teacher',
    // Multi Branch
    MULTI_BRANCH_OVERVIEW: '/super-admin/multi-branch/overview',
    BRANCH_LIST: '/super-admin/multi-branch/overview',
    ADD_BRANCH: '/super-admin/multi-branch/add',
    EDIT_BRANCH: '/super-admin/multi-branch/edit/:id',
    BRANCH_SETTINGS_ROOT: '/super-admin/multi-branch/settings',
    BRANCH_SETTINGS: '/super-admin/multi-branch/settings/:id',
    BRANCH_REPORT: '/super-admin/multi-branch/report',
    // Zoom Live Classes
    ZOOM_CLASSES: '/super-admin/zoom-live-classes/classes',
    ZOOM_MEETING: '/super-admin/zoom-live-classes/meeting',
    ZOOM_REPORTS: '/super-admin/zoom-live-classes/reports',
    ZOOM_SETTINGS: '/super-admin/zoom-live-classes/settings',

    // Student Info
    STUDENT_ADMISSION: '/super-admin/student-information/admission',
    ADMISSION_FORM_SETTINGS: '/super-admin/student-information/admission-form-settings',
    STUDENT_PROFILE: '/super-admin/student-information/profile/:studentId',
    STUDENT_DETAILS: '/super-admin/student-information/details',
    EDIT_STUDENT: '/super-admin/student-information/edit/:id',
    ONLINE_ADMISSION_LIST: '/super-admin/student-information/online-admission',
    EDIT_ONLINE_ADMISSION: '/super-admin/student-information/online-admission/edit/:id',
    // STUDENT_CATEGORIES and STUDENT_HOUSE moved to Admission Form Settings tabs
    DISABLED_STUDENTS: '/super-admin/student-information/disabled-students',
    DISABLE_REASON: '/super-admin/student-information/disable-reason',
    MULTI_CLASS_STUDENT: '/super-admin/student-information/multi-class',
    BULK_DELETE: '/super-admin/student-information/bulk-delete',
    STUDENT_BULK_UPLOAD: '/super-admin/student-information/bulk-upload',
    STUDENT_PROMOTION: '/super-admin/student-information/promotion',
    STUDENT_ID_CARD: '/super-admin/student-information/id-card',
    // Behaviour
    ASSIGN_INCIDENT: '/super-admin/behaviour-records/assign-incident',
    INCIDENTS: '/super-admin/behaviour-records/incidents',
    BEHAVIOUR_REPORTS: '/super-admin/behaviour-records/reports',
    BEHAVIOUR_SETTING: '/super-admin/behaviour-records/setting',
    // Attendance
    STUDENT_ATTENDANCE: '/super-admin/attendance/student-attendance',
    ATTENDANCE_BY_DATE: '/super-admin/attendance/attendance-by-date',
    APPROVE_LEAVE: '/super-admin/attendance/approve-student-leave',
    STAFF_ATTENDANCE: '/super-admin/attendance/staff-attendance',
    ATTENDANCE_REPORT: '/super-admin/attendance/attendance-report',
    // Advanced Attendance (Futuristic Module)
    LIVE_ATTENDANCE_DASHBOARD: '/super-admin/attendance/live-dashboard',
    QR_CODE_GENERATOR: '/super-admin/attendance/qr-generator',
    DEVICE_MANAGEMENT: '/super-admin/attendance/device-management',
    CARD_MANAGEMENT: '/super-admin/attendance/card-management',
    FACE_REGISTRATION: '/super-admin/attendance/face-registration',
    LIVE_FACE_ATTENDANCE: '/super-admin/attendance/live-face-attendance',
    ATTENDANCE_RULES: '/super-admin/attendance/rules',
    GEO_FENCE_SETUP: '/super-admin/attendance/geo-fence',
    WEARABLE_DEVICES: '/super-admin/attendance/wearable-devices',
    ATTENDANCE_ANALYTICS: '/super-admin/attendance/analytics',
    // Examinations
    EXAM_GROUP: '/super-admin/examinations/exam-group',
    EXAM_LIST: '/super-admin/examinations/exam-list',
    EXAM_SCHEDULE: '/super-admin/examinations/exam-schedule',
    EXAM_ATTENDANCE: '/super-admin/examinations/exam-attendance',
    MARKS_ENTRY: '/super-admin/examinations/marks-entry',
    MARKS_DIVISION: '/super-admin/examinations/marks-division',
    MARKS_GRADE: '/super-admin/examinations/marks-grade',
    GENERAL_EXAM_RESULT: '/super-admin/examinations/general-exam-result',
    GENERAL_EXAM_SCHEDULE: '/super-admin/examinations/general-exam-schedule',
    CBSE_EXAM: '/super-admin/examinations/cbse-exam',
    CBSE_SETTINGS: '/super-admin/examinations/cbse-settings',
    CBSE_TERM: '/super-admin/examinations/cbse-term',
    CBSE_ASSESSMENT: '/super-admin/examinations/cbse-assessment',
    CBSE_OBSERVATION: '/super-admin/examinations/cbse-observation',
    CBSE_OBSERVATION_PARAM: '/super-admin/examinations/cbse-observation-parameter',
    CBSE_EXAM_GRADE: '/super-admin/examinations/cbse-exam-grade',
    ADD_EXAM_SUBJECTS: '/super-admin/examinations/add-exam-subjects',
    ASSIGN_STUDENTS: '/super-admin/examinations/assign-students',
    ENTER_MARKS: '/super-admin/examinations/enter-marks',
    LINK_EXAM: '/super-admin/examinations/link-exam',
    GENERATE_RANK: '/super-admin/examinations/generate-rank',
    GENERATE_TEMPLATE_RANK: '/super-admin/examinations/generate-template-rank',
    MARKSHEET_TEMPLATE: '/super-admin/examinations/marksheet-template',
    PRINT_MARKSHEET: '/super-admin/examinations/print-marksheet',
    PRINT_MARKSHEET_GENERAL: '/super-admin/examinations/print-marksheet-general',
    PRINT_ADMIT_CARD: '/super-admin/examinations/print-admit-card',
    DESIGN_MARKSHEET: '/super-admin/examinations/design-marksheet',
    DESIGN_ADMIT_CARD: '/super-admin/examinations/design-admit-card',
    TEACHER_REMARKS: '/super-admin/examinations/teacher-remarks',
    ASSIGN_OBSERVATION: '/super-admin/examinations/assign-observation',
    CBSE_REPORTS: '/super-admin/examinations/cbse-reports',
    REPORT_CARD: '/super-admin/examinations/report-card',
    // Fees
    FEES_GROUP: '/super-admin/fees-collection/fees-group',
    FEES_TYPE: '/super-admin/fees-collection/fees-type',
    FEES_MASTER: '/super-admin/fees-collection/fees-master',
    ASSIGN_FEE_MASTER: '/super-admin/fees-collection/master/:masterId/assign',
    ASSIGN_FEE_GROUP: '/super-admin/fees-collection/assign-fee-group',
    COLLECT_FEES: '/super-admin/fees-collection/collect-fees',
    STUDENT_FEES: '/super-admin/fees-collection/student-fees/:studentId',
    SEARCH_FEES_PAYMENT: '/super-admin/fees-collection/search-fees-payment',
    SEARCH_DUE_FEES: '/super-admin/fees-collection/search-due-fees',
    FEES_DISCOUNT: '/super-admin/fees-collection/fees-discount',
    FEES_CARRY_FORWARD: '/super-admin/fees-collection/fees-carry-forward',
    FEES_REMINDER: '/super-admin/fees-collection/fees-reminder',
    PRINT_FEES_RECEIPT: '/super-admin/fees-collection/print-fees-receipt/:paymentId',
    PRINT_SELECTED_FEES: '/super-admin/fees-collection/print-selected-fees',
    QUICK_FEES: '/super-admin/fees-collection/quick-fees',
    OFFLINE_PAYMENT: '/super-admin/fees-collection/offline-bank-payments',
    ONLINE_PAYMENT: '/super-admin/fees-collection/online-payment',
    // Finance
    EXPENSE_HEAD: '/super-admin/finance/expense-head',
    EXPENSE: '/super-admin/finance/expense',
    ADD_EXPENSE: '/super-admin/finance/add-expense',
    SEARCH_EXPENSE: '/super-admin/finance/search-expense',
    INCOME_HEAD: '/super-admin/finance/income-head',
    INCOME: '/super-admin/finance/income',
    ADD_INCOME: '/super-admin/finance/add-income',
    SEARCH_INCOME: '/super-admin/finance/search-income',
    // HR
    EMPLOYEE_FORM_SETTINGS: '/super-admin/human-resource/employee-form-settings',
    DEPARTMENTS: '/super-admin/human-resource/departments',
    EMPLOYMENT_CATEGORY: '/super-admin/human-resource/employment-category',
    DESIGNATIONS: '/super-admin/human-resource/designations',
    ADD_EMPLOYEE: '/super-admin/human-resource/employee/add',
    EDIT_EMPLOYEE: '/super-admin/human-resource/employee/edit/:employeeId',
    EMPLOYEE_LIST: '/super-admin/human-resource/employees',
    STAFF_DIRECTORY: '/super-admin/human-resource/staff-directory',
    STAFF_PROFILE: '/super-admin/human-resource/staff-profile/:employeeId',
    IMPORT_STAFF: '/super-admin/human-resource/import-staff',
    STAFF_LEAVE_TYPE: '/super-admin/human-resource/staff-leave-type',
    STAFF_APPLY_LEAVE: '/super-admin/human-resource/staff-apply-leave',
    APPROVE_STAFF_LEAVE: '/super-admin/human-resource/approve-staff-leave',
    EMPLOYEE_DOCUMENTS: '/super-admin/human-resource/employee-documents',
    EMPLOYEE_PERFORMANCE: '/super-admin/human-resource/employee-performance',
    EMPLOYEE_PAYROLL: '/super-admin/human-resource/payroll',
    ADD_STAFF: '/super-admin/human-resource/add-staff',
    LEAVE_MANAGEMENT: '/super-admin/human-resource/leave-management',
    HR_STAFF_ID_CARD: '/super-admin/human-resource/staff-id-card',
    // Library
    LIBRARY_BOOKS: '/super-admin/library/books',
    LIBRARY_BOOK_ISSUED: '/super-admin/library/book-issued',
    LIBRARY_MEMBERS: '/super-admin/library/members',
    LIBRARY_ISSUE_RETURN: '/super-admin/library/issue-return',
    LIBRARY_ADD_BOOK: '/super-admin/library/add-book',
    LIBRARY_BOOK_LIST: '/super-admin/library/book-list',
    LIBRARY_CARD: '/super-admin/library/library-card',
    // Hostel
    HOSTELS: '/super-admin/hostel/hostels',
    HOSTEL_ROOMS: '/super-admin/hostel/hostel-rooms',
    ROOM_TYPES: '/super-admin/hostel/room-types',
    HOSTEL_FEE: '/super-admin/hostel/hostel-fee',
    // Transport
    TRANSPORT_ROUTES: '/super-admin/transport/transport-routes',
    TRANSPORT_VEHICLES: '/super-admin/transport/transport-vehicles',
    PICKUP_POINTS: '/super-admin/transport/pickup-points',
    ROUTE_PICKUP_POINT: '/super-admin/transport/route-pickup-point',
    ASSIGN_VEHICLE: '/super-admin/transport/assign-vehicle',
    STUDENT_TRANSPORT_FEES: '/super-admin/transport/student-transport-fees',
    TRANSPORT_FEES_MASTER: '/super-admin/transport/transport-fees-master',
    TRANSPORT_FEE: '/super-admin/transport/transport-fee',
    // Communicate
    NOTICE_BOARD: '/super-admin/communicate/notice-board',
    SEND_EMAIL: '/super-admin/communicate/send-email',
    SEND_SMS: '/super-admin/communicate/send-sms',
    COMPOSE_MESSAGE: '/super-admin/communicate/compose-message',
    EMAIL_SMS_LOG: '/super-admin/communicate/email-sms-log',
    WHATSAPP: '/super-admin/communicate/whatsapp',
    PUSH_NOTIFICATION: '/super-admin/communicate/push-notification',
    // QR
    QR_ATTENDANCE_SETTING: '/super-admin/qr-code-attendance/setting',
    QR_ATTENDANCE_SCAN: '/super-admin/qr-code-attendance/scan',
    // Reports
    REPORT_ATTENDANCE: '/super-admin/reports/attendance-report',
    REPORT_STUDENT_ATT_TYPE: '/super-admin/reports/student-attendance-type-report',
    REPORT_BALANCE_FEES: '/super-admin/reports/balance-fees-report',
    REPORT_BALANCE_FEES_STMT: '/super-admin/reports/balance-fees-statement-report',
    REPORT_BALANCE_FEES_REMARK: '/super-admin/reports/balance-fees-with-remark-report',
    REPORT_DAILY_COLLECTION: '/super-admin/reports/daily-collection-report',
    REPORT_FEES_COLLECTION: '/super-admin/reports/fees-collection-report',
    REPORT_FEES_STATEMENT: '/super-admin/reports/fees-statement-report',
    REPORT_INC_EXP_BALANCE: '/super-admin/reports/income-expense-balance-report',
    REPORT_INCOME: '/super-admin/reports/income-report',
    REPORT_EXPENSE: '/super-admin/reports/expense-report',
    REPORT_INCOME_GROUP: '/super-admin/reports/income-group-report',
    REPORT_EXPENSE_GROUP: '/super-admin/reports/expense-group-report',
    REPORT_ONLINE_FEES: '/super-admin/reports/online-fees-collection-report',
    REPORT_PAYROLL: '/super-admin/reports/payroll-report',
    REPORT_STUDENT_INFO: '/super-admin/reports/student-information-report',
    REPORT_HOMEWORK: '/super-admin/reports/homework-report',
    REPORT_HOMEWORK_EVAL: '/super-admin/reports/homework-evaluation-report',
    REPORT_HOSTEL: '/super-admin/reports/hostel-report',
    REPORT_TRANSPORT: '/super-admin/reports/student-transport-report',
    REPORT_PARENT_LOGIN: '/super-admin/reports/parent-login-credential-report',
    REPORT_LIB_BOOK_ISSUE: '/super-admin/reports/library/book-issue',
    REPORT_LIB_BOOK_DUE: '/super-admin/reports/library/book-due',
    REPORT_LIB_BOOK_INV: '/super-admin/reports/library/book-inventory',
    REPORT_LIB_ISSUE_RETURN: '/super-admin/reports/library/book-issue-return',
    // System Settings
    SETTINGS_GENERAL: '/super-admin/system-settings/general-setting',
    SETTINGS_SESSION: '/super-admin/system-settings/session-setting',
    SETTINGS_ROLE_PERMISSION: '/super-admin/system-settings/role-permission',
    SETTINGS_PROFILE_UPDATE: '/super-admin/system-settings/student-profile-update-settings',
    SETTINGS_PRINT_HEADER: '/super-admin/system-settings/print-header-footer',
    SETTINGS_ONLINE_ADMISSION: '/super-admin/system-settings/online-admission-setting',
    SETTINGS_EMAIL: '/super-admin/system-settings/email-setting',
    SETTINGS_SMS: '/super-admin/system-settings/sms-setting',
    SETTINGS_NOTIFICATION: '/super-admin/system-settings/notification-setting',
    SETTINGS_PAYMENT_GATEWAY: '/super-admin/system-settings/payment-methods',
    SETTINGS_BACKUP: '/super-admin/system-settings/backup-restore',
    // Homework
    HOMEWORK_LIST: '/super-admin/homework/list',
    ADD_HOMEWORK: '/super-admin/homework/add-homework',
    HOMEWORK: '/super-admin/homework/homework-list',
    EVALUATE_HOMEWORK: '/super-admin/homework/evaluate-homework',
    MANAGE_LESSONS: '/super-admin/lesson-plan/manage-lessons',
    SYLLABUS_STATUS: '/super-admin/lesson-plan/syllabus-status',
    // Inventory
    INV_ADD_ITEM: '/super-admin/inventory/add-item',
    INV_ADD_STOCK: '/super-admin/inventory/add-item-stock',
    INV_ISSUE_ITEM: '/super-admin/inventory/issue-item',
    INV_CATEGORY: '/super-admin/inventory/item-category',
    INV_STORE: '/super-admin/inventory/item-store',
    INV_SUPPLIER: '/super-admin/inventory/item-supplier',
    INV_ITEM_STOCK: '/super-admin/inventory/item-stock',
    // Certificate
    CERT_TEMPLATES: '/super-admin/certificate/certificate-templates',
    CERT_GENERATE: '/super-admin/certificate/generate-certificate',
    CERT_HISTORY: '/super-admin/certificate/certificate-history',
    CERT_STUDENT: '/super-admin/certificate/student-certificate',
    CERT_GENERATE_ID: '/super-admin/certificate/generate-id-card',
    CERT_STAFF_ID: '/super-admin/certificate/staff-id-card',
    CERT_GENERATE_STAFF_ID: '/super-admin/certificate/generate-staff-id-card',
    CERT_STUDENT_ID: '/super-admin/certificate/student-id-card',
    // Alumni
    ALUMNI_LIST: '/super-admin/alumni/list',
    ALUMNI_EVENTS: '/super-admin/alumni/alumni-events',
    // Download Center
    DOWNLOAD_CENTER: '/super-admin/download-center',
  },
  STUDENT: {
    DASHBOARD: '/Student/dashboard',
    PROFILE: '/Student/profile',
    EDIT_PROFILE: '/Student/edit-profile',
    FEES: '/Student/fees',
    EXAM_SCHEDULE: '/Student/exam-schedule',
    EXAM_RESULT: '/Student/exam-result',
    HOSTEL_ROOMS: '/Student/hostel-rooms',
    TRANSPORT_ROUTES: '/Student/transport-routes',
    TIMETABLE: '/Student/timetable',
    HOMEWORK: '/Student/homework',
    SYLLABUS: '/Student/syllabus',
    LIBRARY: '/Student/library',
    ATTENDANCE: '/Student/attendance',
    APPLY_LEAVE: '/Student/apply-leave',
  },
  PARENT: {
    DASHBOARD: '/Parent/dashboard',
  },
  TEACHER: {
    DASHBOARD: '/Teacher/dashboard',
  },
  ADMIN: {
    DASHBOARD: '/Admin/dashboard',
  },
  PRINCIPAL: {
    DASHBOARD: '/Principal/dashboard',
  },
  ACCOUNTANT: {
    DASHBOARD: '/Accountant/dashboard',
  },
  RECEPTIONIST: {
    DASHBOARD: '/Receptionist/dashboard',
  },
  LIBRARIAN: {
    DASHBOARD: '/Librarian/dashboard',
  },
  STAFF: {
    DASHBOARD: '/super-admin/dashboard',
    RECEPTIONIST: '/Receptionist/dashboard',
    LIBRARIAN: '/Librarian/dashboard',
    ACCOUNTANT: '/Accountant/dashboard',
    PRINCIPAL: '/Principal/dashboard',
  }
};

export const getRoute = (category, key) => {
  return ROUTES[category]?.[key] || '#';
};

export const validateRoute = (path) => {
  const allValues = Object.values(ROUTES).flatMap(obj => Object.values(obj));
  return allValues.includes(path);
};

