import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Take control of the page immediately
// self.skipWaiting();
// clientsClaim();

// ---------------------------------------------------------------------------
// Push Notification Logic
// ---------------------------------------------------------------------------

self.addEventListener('push', (event) => {
  let data = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { title: 'New Notification', body: event.data.text() };
    }
  }

  const title = data.title || 'Jashchar ERP';
  const options = {
    body: data.body || 'You have a new update.',
    icon: '/pwa-192x192.png', // Ensure these icons exist in public/
    badge: '/pwa-192x192.png',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/',
    },
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // Otherwise open a new window
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});

// ---------------------------------------------------------------------------
// Offline Fallback (Optional - for specific routes)
// ---------------------------------------------------------------------------
// You can add runtime caching here using workbox-routing and workbox-strategies
// Example: Cache API calls
// import { registerRoute } from 'workbox-routing';
// import { NetworkFirst } from 'workbox-strategies';
// registerRoute(
//   ({ url }) => url.pathname.startsWith('/api'),
//   new NetworkFirst()
// );
