/**
 * Fees Report Generator - Template Definitions
 * Module 11: 40 Fee Report Templates across 3 categories
 * 
 * Categories:
 * 1. Student Fee Reports (15)
 * 2. Collection Analysis (15)
 * 3. Special Fee Reports (10)
 */

import { COLUMN_SETS, getColumns } from './columns';

// ═══════════════════════════════════════════════════════════════════════════════
// TEMPLATE DEFINITIONS
// ═══════════════════════════════════════════════════════════════════════════════

export const FEES_TEMPLATES = [
  // ─────────────────────────────────────────────────────────────────────────────
  // CATEGORY 1: STUDENT FEE REPORTS (15)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'student_fee_ledger',
    name: 'Student Fee Ledger',
    description: 'Complete fee ledger for each student with all fee heads',
    category: 'student_fee',
    icon: '📖',
    columns: getColumns(COLUMN_SETS.student_fee_ledger),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'student_name', direction: 'asc' }],
    aggregations: ['total_fee', 'paid_amount', 'due_amount'],
    popular: true,
  },
  {
    id: 'fee_structure_allocation',
    name: 'Fee Structure Allocation',
    description: 'Fee structure assigned to each student with discounts',
    category: 'student_fee',
    icon: '📋',
    columns: getColumns(COLUMN_SETS.fee_structure_allocation),
    defaultFilters: {},
    defaultGroupBy: ['fee_structure_name'],
    defaultSortBy: [{ field: 'class_name', direction: 'asc' }],
    aggregations: ['annual_fee', 'discount_amount', 'net_payable'],
    popular: true,
  },
  {
    id: 'individual_fee_statement',
    name: 'Individual Fee Statement',
    description: 'Detailed payment history for a single student',
    category: 'student_fee',
    icon: '📄',
    columns: getColumns(COLUMN_SETS.individual_fee_statement),
    defaultFilters: {},
    defaultGroupBy: [],
    defaultSortBy: [{ field: 'receipt_date', direction: 'desc' }],
    aggregations: ['paid_amount'],
    requiresStudentFilter: true,
  },
  {
    id: 'fee_dues_summary',
    name: 'Fee Dues Summary',
    description: 'All students with pending fees and contact details',
    category: 'student_fee',
    icon: '⚠️',
    columns: getColumns(COLUMN_SETS.fee_dues_summary),
    defaultFilters: { has_dues: true },
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'due_amount', direction: 'desc' }],
    aggregations: ['total_fee', 'paid_amount', 'due_amount'],
    popular: true,
  },
  {
    id: 'student_wise_fee',
    name: 'Student-wise Fee Report',
    description: 'Fee status for all students with parent contact',
    category: 'student_fee',
    icon: '👨‍🎓',
    columns: getColumns(COLUMN_SETS.student_wise_fee),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'student_name', direction: 'asc' }],
    aggregations: ['total_fee', 'paid_amount', 'due_amount'],
  },
  {
    id: 'installment_status',
    name: 'Installment-wise Status',
    description: 'Installment payment status for all students',
    category: 'student_fee',
    icon: '📅',
    columns: getColumns(COLUMN_SETS.installment_status),
    defaultFilters: {},
    defaultGroupBy: ['installment_no'],
    defaultSortBy: [{ field: 'due_date', direction: 'asc' }],
    aggregations: ['paid_amount', 'due_amount', 'late_fee'],
  },
  {
    id: 'fee_head_breakup',
    name: 'Fee Head-wise Breakup',
    description: 'Student fees broken down by each fee head',
    category: 'student_fee',
    icon: '📊',
    columns: getColumns(COLUMN_SETS.fee_head_breakup),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'total_fee', direction: 'desc' }],
    aggregations: ['tuition_fee', 'transport_fee', 'library_fee', 'lab_fee', 'exam_fee', 'total_fee'],
  },
  {
    id: 'payment_history',
    name: 'Payment History',
    description: 'Complete payment transaction history',
    category: 'student_fee',
    icon: '📜',
    columns: getColumns(COLUMN_SETS.payment_history),
    defaultFilters: {},
    defaultGroupBy: [],
    defaultSortBy: [{ field: 'receipt_date', direction: 'desc' }],
    aggregations: ['paid_amount'],
    popular: true,
  },
  {
    id: 'pending_fee_alerts',
    name: 'Pending Fee Alerts',
    description: 'Students with overdue fees requiring follow-up',
    category: 'student_fee',
    icon: '🔔',
    columns: getColumns(COLUMN_SETS.pending_fee_alerts),
    defaultFilters: { overdue: true },
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'overdue_days', direction: 'desc' }],
    aggregations: ['due_amount'],
    popular: true,
  },
  {
    id: 'fee_waiver_list',
    name: 'Fee Waiver List',
    description: 'Students with fee waivers and discount details',
    category: 'student_fee',
    icon: '🎁',
    columns: getColumns(COLUMN_SETS.fee_waiver_list),
    defaultFilters: { has_discount: true },
    defaultGroupBy: ['discount_type'],
    defaultSortBy: [{ field: 'discount_amount', direction: 'desc' }],
    aggregations: ['total_fee', 'discount_amount', 'net_payable'],
  },
  {
    id: 'category_wise_fees',
    name: 'Category-wise Fees',
    description: 'Fee summary grouped by student category',
    category: 'student_fee',
    icon: '📁',
    columns: getColumns(COLUMN_SETS.category_wise_fees),
    defaultFilters: {},
    defaultGroupBy: ['category'],
    defaultSortBy: [{ field: 'total_fee', direction: 'desc' }],
    aggregations: ['student_count', 'total_fee', 'paid_amount', 'due_amount'],
  },
  {
    id: 'new_admission_fees',
    name: 'New Admission Fees',
    description: 'Fee status for newly admitted students',
    category: 'student_fee',
    icon: '🆕',
    columns: getColumns(COLUMN_SETS.new_admission_fees),
    defaultFilters: { is_new_admission: true },
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'admission_date', direction: 'desc' }],
    aggregations: ['admission_fee', 'one_time_fee', 'total_fee', 'paid_amount', 'due_amount'],
  },
  {
    id: 'sibling_fee_summary',
    name: 'Sibling Fee Summary',
    description: 'Fee details for families with multiple children',
    category: 'student_fee',
    icon: '👨‍👩‍👧‍👦',
    columns: getColumns(COLUMN_SETS.sibling_fee_summary),
    defaultFilters: { has_sibling: true },
    defaultGroupBy: ['father_name'],
    defaultSortBy: [{ field: 'discount_amount', direction: 'desc' }],
    aggregations: ['total_fee', 'discount_amount', 'net_payable', 'paid_amount'],
  },
  {
    id: 'tc_fee_closure',
    name: 'TC Issued Fee Closure',
    description: 'Fee settlement for students who left (TC issued)',
    category: 'student_fee',
    icon: '📤',
    columns: getColumns(COLUMN_SETS.tc_fee_closure),
    defaultFilters: { status: 'tc_issued' },
    defaultGroupBy: [],
    defaultSortBy: [{ field: 'balance', direction: 'desc' }],
    aggregations: ['total_fee', 'paid_amount', 'refund_amount', 'balance'],
  },
  {
    id: 'fee_revision_impact',
    name: 'Fee Revision Impact',
    description: 'Impact analysis of fee structure changes',
    category: 'student_fee',
    icon: '📈',
    columns: getColumns(COLUMN_SETS.fee_revision_impact),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'total_impact', direction: 'desc' }],
    aggregations: ['student_count', 'total_impact'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // CATEGORY 2: COLLECTION ANALYSIS (15)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'daily_collection',
    name: 'Daily Collection Report',
    description: 'Day-wise fee collection with receipt details',
    category: 'collection_analysis',
    icon: '📅',
    columns: getColumns(COLUMN_SETS.daily_collection),
    defaultFilters: { date_range: 'today' },
    defaultGroupBy: ['receipt_date'],
    defaultSortBy: [{ field: 'receipt_no', direction: 'desc' }],
    aggregations: ['paid_amount'],
    popular: true,
  },
  {
    id: 'monthly_collection_summary',
    name: 'Monthly Collection Summary',
    description: 'Month-wise collection vs expected analysis',
    category: 'collection_analysis',
    icon: '📊',
    columns: getColumns(COLUMN_SETS.monthly_collection_summary),
    defaultFilters: {},
    defaultGroupBy: ['month'],
    defaultSortBy: [{ field: 'month', direction: 'asc' }],
    aggregations: ['expected_collection', 'actual_collection'],
    popular: true,
  },
  {
    id: 'class_wise_collection',
    name: 'Class-wise Collection',
    description: 'Fee collection summary by class',
    category: 'collection_analysis',
    icon: '🏫',
    columns: getColumns(COLUMN_SETS.class_wise_collection),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'class_name', direction: 'asc' }],
    aggregations: ['total_fee', 'paid_amount', 'due_amount'],
    popular: true,
  },
  {
    id: 'payment_mode_analysis',
    name: 'Payment Mode Analysis',
    description: 'Collection breakdown by payment mode',
    category: 'collection_analysis',
    icon: '💳',
    columns: getColumns(COLUMN_SETS.payment_mode_analysis),
    defaultFilters: {},
    defaultGroupBy: ['payment_mode'],
    defaultSortBy: [{ field: 'total_amount', direction: 'desc' }],
    aggregations: ['transaction_count', 'total_amount'],
  },
  {
    id: 'collector_wise',
    name: 'Collector-wise Report',
    description: 'Collection summary by fee collector',
    category: 'collection_analysis',
    icon: '👤',
    columns: getColumns(COLUMN_SETS.collector_wise),
    defaultFilters: {},
    defaultGroupBy: ['collected_by'],
    defaultSortBy: [{ field: 'total_collection', direction: 'desc' }],
    aggregations: ['receipt_count', 'total_collection'],
  },
  {
    id: 'fee_head_collection',
    name: 'Fee Head Collection',
    description: 'Collection status by fee type/head',
    category: 'collection_analysis',
    icon: '📑',
    columns: getColumns(COLUMN_SETS.fee_head_collection),
    defaultFilters: {},
    defaultGroupBy: ['fee_head'],
    defaultSortBy: [{ field: 'collected_amount', direction: 'desc' }],
    aggregations: ['expected_amount', 'collected_amount', 'pending_amount'],
  },
  {
    id: 'quarter_wise_summary',
    name: 'Quarter-wise Summary',
    description: 'Quarterly fee collection analysis',
    category: 'collection_analysis',
    icon: '📆',
    columns: getColumns(COLUMN_SETS.quarter_wise_summary),
    defaultFilters: {},
    defaultGroupBy: ['quarter'],
    defaultSortBy: [{ field: 'quarter', direction: 'asc' }],
    aggregations: ['expected_collection', 'actual_collection'],
  },
  {
    id: 'trend_analysis',
    name: 'Trend Analysis',
    description: 'Year-over-year collection trend comparison',
    category: 'collection_analysis',
    icon: '📈',
    columns: getColumns(COLUMN_SETS.trend_analysis),
    defaultFilters: {},
    defaultGroupBy: ['month'],
    defaultSortBy: [{ field: 'month', direction: 'asc' }],
    aggregations: ['current_year_collection', 'previous_year_collection'],
    popular: true,
  },
  {
    id: 'target_vs_achievement',
    name: 'Target vs Achievement',
    description: 'Collection target achievement tracking',
    category: 'collection_analysis',
    icon: '🎯',
    columns: getColumns(COLUMN_SETS.target_vs_achievement),
    defaultFilters: {},
    defaultGroupBy: [],
    defaultSortBy: [{ field: 'month', direction: 'asc' }],
    aggregations: ['target_amount', 'achieved_amount'],
  },
  {
    id: 'peak_collection_days',
    name: 'Peak Collection Days',
    description: 'Identify high-collection days for planning',
    category: 'collection_analysis',
    icon: '📌',
    columns: getColumns(COLUMN_SETS.peak_collection_days),
    defaultFilters: {},
    defaultGroupBy: ['day_name'],
    defaultSortBy: [{ field: 'total_collection', direction: 'desc' }],
    aggregations: ['receipt_count', 'total_collection'],
  },
  {
    id: 'online_payments',
    name: 'Online Payment Report',
    description: 'All online payment transactions',
    category: 'collection_analysis',
    icon: '🌐',
    columns: getColumns(COLUMN_SETS.online_payments),
    defaultFilters: { payment_mode: 'Online' },
    defaultGroupBy: ['payment_gateway'],
    defaultSortBy: [{ field: 'receipt_date', direction: 'desc' }],
    aggregations: ['paid_amount'],
    popular: true,
  },
  {
    id: 'cheque_status',
    name: 'Cheque Status Report',
    description: 'Track cheque payments and clearance status',
    category: 'collection_analysis',
    icon: '🏦',
    columns: getColumns(COLUMN_SETS.cheque_status),
    defaultFilters: { payment_mode: 'Cheque' },
    defaultGroupBy: ['status'],
    defaultSortBy: [{ field: 'cheque_date', direction: 'desc' }],
    aggregations: ['amount'],
  },
  {
    id: 'receipt_register',
    name: 'Receipt Register',
    description: 'Complete receipt log for audit',
    category: 'collection_analysis',
    icon: '📝',
    columns: getColumns(COLUMN_SETS.receipt_register),
    defaultFilters: {},
    defaultGroupBy: [],
    defaultSortBy: [{ field: 'receipt_no', direction: 'desc' }],
    aggregations: ['paid_amount'],
    popular: true,
  },
  {
    id: 'cancelled_receipts',
    name: 'Cancelled Receipt Report',
    description: 'List of cancelled receipts with reasons',
    category: 'collection_analysis',
    icon: '❌',
    columns: getColumns(COLUMN_SETS.cancelled_receipts),
    defaultFilters: { is_cancelled: true },
    defaultGroupBy: ['cancel_reason'],
    defaultSortBy: [{ field: 'cancel_date', direction: 'desc' }],
    aggregations: ['original_amount'],
  },
  {
    id: 'collection_comparison',
    name: 'Collection Comparison',
    description: 'Compare collections across periods',
    category: 'collection_analysis',
    icon: '⚖️',
    columns: getColumns(COLUMN_SETS.collection_comparison),
    defaultFilters: {},
    defaultGroupBy: ['comparison_period'],
    defaultSortBy: [{ field: 'difference', direction: 'desc' }],
    aggregations: ['period_1_collection', 'period_2_collection'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // CATEGORY 3: SPECIAL FEE REPORTS (10)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'transport_fee',
    name: 'Transport Fee Report',
    description: 'Transport fee collection by route and stop',
    category: 'special_fee',
    icon: '🚌',
    columns: getColumns(COLUMN_SETS.transport_fee),
    defaultFilters: {},
    defaultGroupBy: ['route_name'],
    defaultSortBy: [{ field: 'route_name', direction: 'asc' }],
    aggregations: ['transport_fee', 'paid_amount', 'due_amount'],
    popular: true,
  },
  {
    id: 'hostel_fee',
    name: 'Hostel Fee Report',
    description: 'Hostel and mess fee collection status',
    category: 'special_fee',
    icon: '🏠',
    columns: getColumns(COLUMN_SETS.hostel_fee),
    defaultFilters: {},
    defaultGroupBy: ['hostel_name'],
    defaultSortBy: [{ field: 'hostel_name', direction: 'asc' }],
    aggregations: ['hostel_fee', 'mess_fee', 'paid_amount', 'due_amount'],
    popular: true,
  },
  {
    id: 'library_fine',
    name: 'Library Fine Report',
    description: 'Library late return fines and collection',
    category: 'special_fee',
    icon: '📚',
    columns: getColumns(COLUMN_SETS.library_fine),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'fine_amount', direction: 'desc' }],
    aggregations: ['fine_amount'],
  },
  {
    id: 'lab_fee_collection',
    name: 'Lab Fee Collection',
    description: 'Laboratory fee collection by lab type',
    category: 'special_fee',
    icon: '🔬',
    columns: getColumns(COLUMN_SETS.lab_fee_collection),
    defaultFilters: {},
    defaultGroupBy: ['lab_type'],
    defaultSortBy: [{ field: 'total_fee', direction: 'desc' }],
    aggregations: ['total_fee', 'collected_amount', 'pending_amount'],
  },
  {
    id: 'exam_fee_status',
    name: 'Exam Fee Status',
    description: 'Examination fee payment status',
    category: 'special_fee',
    icon: '📝',
    columns: getColumns(COLUMN_SETS.exam_fee_status),
    defaultFilters: {},
    defaultGroupBy: ['exam_name'],
    defaultSortBy: [{ field: 'total_amount', direction: 'desc' }],
    aggregations: ['exam_fee', 'late_fee', 'total_amount', 'paid_amount'],
  },
  {
    id: 'activity_fee',
    name: 'Activity Fee Report',
    description: 'Extra-curricular activity fee collection',
    category: 'special_fee',
    icon: '🎨',
    columns: getColumns(COLUMN_SETS.activity_fee),
    defaultFilters: {},
    defaultGroupBy: ['activity_name'],
    defaultSortBy: [{ field: 'activity_fee', direction: 'desc' }],
    aggregations: ['activity_fee', 'paid_amount'],
  },
  {
    id: 'sports_fee',
    name: 'Sports Fee Collection',
    description: 'Sports and equipment fee collection',
    category: 'special_fee',
    icon: '⚽',
    columns: getColumns(COLUMN_SETS.sports_fee),
    defaultFilters: {},
    defaultGroupBy: ['sport_name'],
    defaultSortBy: [{ field: 'total_amount', direction: 'desc' }],
    aggregations: ['sports_fee', 'equipment_fee', 'total_amount', 'paid_amount'],
  },
  {
    id: 'development_fund',
    name: 'Development Fund Report',
    description: 'School development fund collection',
    category: 'special_fee',
    icon: '🏗️',
    columns: getColumns(COLUMN_SETS.development_fund),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'total_expected', direction: 'desc' }],
    aggregations: ['total_expected', 'collected_amount', 'pending_amount'],
  },
  {
    id: 'late_fee_collection',
    name: 'Late Fee Collection',
    description: 'Late payment penalty collection',
    category: 'special_fee',
    icon: '⏰',
    columns: getColumns(COLUMN_SETS.late_fee_collection),
    defaultFilters: {},
    defaultGroupBy: ['class_name'],
    defaultSortBy: [{ field: 'overdue_days', direction: 'desc' }],
    aggregations: ['late_fee', 'paid_amount'],
  },
  {
    id: 'refund_report',
    name: 'Refund Report',
    description: 'Fee refunds processed with details',
    category: 'special_fee',
    icon: '↩️',
    columns: getColumns(COLUMN_SETS.refund_report),
    defaultFilters: {},
    defaultGroupBy: ['refund_reason'],
    defaultSortBy: [{ field: 'refund_date', direction: 'desc' }],
    aggregations: ['original_paid', 'refund_amount'],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY DEFINITIONS
// ═══════════════════════════════════════════════════════════════════════════════

export const FEES_CATEGORIES = [
  {
    id: 'student_fee',
    name: 'Student Fee Reports',
    icon: '👨‍🎓',
    description: 'Individual and class-wise student fee reports',
    color: 'blue',
    count: 15,
  },
  {
    id: 'collection_analysis',
    name: 'Collection Analysis',
    icon: '📊',
    description: 'Collection trends and analysis reports',
    color: 'green',
    count: 15,
  },
  {
    id: 'special_fee',
    name: 'Special Fee Reports',
    icon: '⭐',
    description: 'Transport, hostel, lab and other special fees',
    color: 'purple',
    count: 10,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════════

// Get templates by category
export const getTemplatesByCategory = (categoryId) => {
  return FEES_TEMPLATES.filter(t => t.category === categoryId);
};

// Get popular templates
export const getPopularTemplates = () => {
  return FEES_TEMPLATES.filter(t => t.popular);
};

// Get template by ID
export const getTemplateById = (templateId) => {
  return FEES_TEMPLATES.find(t => t.id === templateId);
};

// Search templates
export const searchTemplates = (query) => {
  const lowerQuery = query.toLowerCase();
  return FEES_TEMPLATES.filter(t => 
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery)
  );
};

export default {
  FEES_TEMPLATES,
  FEES_CATEGORIES,
  getTemplatesByCategory,
  getPopularTemplates,
  getTemplateById,
  searchTemplates,
};
